---
- name: Converge
  hosts: all
  become: true
  vars:
    skip_systemd: true
    xcaddy_with:
      - "github.com/caddy-dns/loopia"
      - "github.com/caddy-dns/glesys"
    
  tasks:
    - name: "Include caddy"
      ansible.builtin.include_role:
        name: "kmpm.caddy"
