---
# handlers file for caddy

- name: "restart caddy"
  ansible.builtin.systemd:
    name: caddy
    state: restarted
    daemon_reload: true
    enabled: yes
  when:
    - not skip_systemd

- name: "reload ansible_local"
  ansible.builtin.setup:
    filter: "ansible_local"