---
# handlers file for caddy

- name: restart caddy
  systemd:
    name: caddy
    state: restarted
    daemon_reload: true
    enabled: yes

- name: "reload ansible_local"
  setup:
    filter: "ansible_local"