---
- hosts: all
  tasks:
    - name: Make sure required packages are installed
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - net-tools
        - python3-pip
    - name: Make sure that required modules are installled
      pip:
        name: "{{ item }}"
      with_items:
        - github3.py