---
- name: Converge
  hosts: all
  become: true
  vars:
    xcaddy_with:
      - "github.com/caddy-dns/loopia"
    caddy_version: 2.4.6
    skip_systemd: true
  tasks:
    - name: "Include caddy"
      ansible.builtin.include_role:
        name: "kmpm.caddy"
