---
- hosts: all
  tasks:
    - name: update package cache
      apt: 
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Make sure required packages are installed
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - python3-pip
    - name: Make sure that required modules are installled
      pip:
        name: "{{ item }}"
      with_items:
        - github3.py