---
- hosts: all
  tasks:
    - name: Make sure required packages are installed
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - python3-pip
    - name: Make sure that required modules are installled
      ansible.builtin.pip:
        name: "{{ item }}"
      with_items:
        - github3.py