---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: 'kmpm.caddy'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'kmpm.caddy'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint

      - name: Lint code.
        run: |
          yamllint .


  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2004
          - debian10
        scenario: 
          - default
          - custom
          - custom2

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'kmpm.caddy'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: |
          ls -la
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel
          python3 -m pip install -r requirements.txt
      
      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_SCENARIO_NAME: ${{ matrix.scenario }}
        